"'Secure Environments Forms' As screen":
    BackgroundImage: =GreenLayout

    Rectangle4_8 As rectangle:
        Fill: =RGBA(255, 255, 255, 0.6)
        Height: =75
        Width: =137.5
        Y: =657
        ZIndex: =1

    Image20_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =building
        Width: =137.5
        Y: =153
        ZIndex: =2

    Image16_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =coins
        Width: =137.5
        X: =137
        Y: =153
        ZIndex: =3

    Image25_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: ='human-resources'
        Width: =137.5
        Y: =279
        ZIndex: =4

    Image21_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =clipboard
        Width: =137.5
        X: =137
        Y: =279
        ZIndex: =5

    Image22_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =book
        Width: =137.5
        Y: =405
        ZIndex: =6

    Image23_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =advertisement
        Width: =137.5
        X: =137
        Y: =405
        ZIndex: =7

    Image28_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =responsive
        Width: =137.5
        Y: =531
        ZIndex: =8

    Image18_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =community
        Width: =137.5
        X: =137
        Y: =531
        ZIndex: =9

    Image26_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: =padlock
        Width: =137.5
        Y: =657
        ZIndex: =10

    Image27_9 As image:
        BorderColor: =RGBA(32, 54, 71, 1)
        Height: =75
        Image: ='sexual-transmitted-disease'
        Width: =137.5
        X: =137
        Y: =657
        ZIndex: =11

    Label9_8 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.Arial
        FontWeight: =FontWeight.Bold
        Height: =39
        Size: =20
        Text: ="Secure Environments Forms"
        Width: =1034
        X: =274
        Y: =2
        ZIndex: =12

    btn_nav_estates_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('Estates Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        Y: =153
        ZIndex: =13

    btn_nav_finance_15 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('Finance Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        X: =137
        Y: =153
        ZIndex: =14

    btn_nav_hr_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('HR Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        Y: =279
        ZIndex: =15

    btn_nav_ig_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('IG Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        X: =137
        Y: =279
        ZIndex: =16

    btn_nav_learning_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('Learning and Development Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        Y: =405
        ZIndex: =17

    btn_nav_marketing_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('Marketing and Comms Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        X: =137
        Y: =405
        ZIndex: =18

    btn_nav_safeguarding_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('Safeguarding Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        X: =137
        Y: =531
        ZIndex: =19

    btn_nav_secure_env_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('Secure Environments Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        Y: =657
        ZIndex: =20

    btn_nav_sexual_health_8 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('Sexual Health Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        X: =137
        Y: =657
        ZIndex: =21

    btn_nav_finance_16 As button:
        Fill: =RGBA(0,0,0,0)
        Height: =75
        HoverFill: =RGBA(0,0,0,0)
        OnSelect: =Navigate('IT Forms')
        PressedFill: =RGBA(0,0,0,0)
        Text: =""
        Width: =137.5
        Y: =531
        ZIndex: =22

    Icon4_17 As icon.BackArrow:
        Color: =RGBA(255, 255, 255, 1)
        Height: =36
        Icon: =Icon.BackArrow
        OnSelect: =Navigate(Forms)
        Width: =36
        X: =331
        Y: =5
        ZIndex: =23

    Icon4_18 As icon.BackArrow:
        Color: =RGBA(255, 255, 255, 1)
        Height: =36
        Icon: =Icon.Home
        OnSelect: =Navigate(Dashboard)
        Width: =36
        X: =1321
        Y: =3
        ZIndex: =24

    Label11_90 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="Estates"
        Width: =137.5
        Y: =228
        ZIndex: =25

    Label11_91 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="Finance"
        Width: =137.5
        X: =137
        Y: =228
        ZIndex: =26

    Label11_92 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="HR"
        Width: =137.5
        Y: =354
        ZIndex: =27

    Label11_93 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="IG"
        Width: =137.5
        X: =137
        Y: =354
        ZIndex: =28

    Label11_94 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="Learning & Development"
        Width: =137.5
        Y: =480
        ZIndex: =29

    Label11_95 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="Marketing & Comms"
        Width: =137.5
        X: =137
        Y: =480
        ZIndex: =30

    Label11_96 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="IT"
        Width: =137.5
        Y: =606
        ZIndex: =31

    Label11_97 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="Safeguarding"
        Width: =137.5
        X: =137
        Y: =606
        ZIndex: =32

    Label11_98 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="Secure Environments"
        Width: =137.5
        Y: =728
        ZIndex: =33

    Label11_99 As label:
        Align: =Align.Center
        Font: =Font.Arial
        FontWeight: =FontWeight.Lighter
        Size: =10
        Text: ="Sexual Health"
        Width: =137.5
        X: =137
        Y: =728
        ZIndex: =34

